kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    metadata:
      name: config
    controllerManager:
      extraArgs:
        cloud-provider: "external"
    apiServer:
      extraArgs:
        cloud-provider: "external"
    ---
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: "external"
    ---
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: "external"
networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
  kubeProxyMode: "none"
nodes:
  - role: control-plane
  - role: worker
