kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "audit-webhook-config-file": "/etc/kubernetes/policies/sink.yaml"
        "audit-policy-file": "/etc/kubernetes/policies/policy.yaml"
      extraVolumes:
        - name: audit-policies
          hostPath: /etc/kubernetes/policies
          mountPath: /etc/kubernetes/policies
          readOnly: true
          pathType: "DirectoryOrCreate"
networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
  kubeProxyMode: "none"
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: audit
        containerPath: /etc/kubernetes/policies
        readOnly: True
    extraPortMappings:
      - containerPort: 30432
        hostPort: 5432
  - role: worker
