---
apiVersion: v1
kind: Pod
metadata:
  name: "apisnoop"
  labels:
    app.kubernetes.io/name: apisnoop
    app: apisnoop
spec:
  hostname: apisnoop
  hostNetwork: true
  # a mirror pod may not reference service accounts
  # serviceAccountName: default
  securityContext: {}
  volumes:
    - name: tmp
      emptyDir: {}
    - name: var-lib-postgresql
      emptyDir: {}
    - name: var-run-postgresql
      emptyDir: {}
  containers:
    - name: snoopdb
      image: "gcr.io/k8s-staging-apisnoop/snoopdb:v20240121-auditlogger-1.2.11-4-gb17b29c"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: apisnoop
        - name: POSTGRES_USER
          value: apisnoop
        - name: PGDATABASE
          value: apisnoop
        - name: PGUSER
          value: apisnoop
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
      livenessProbe:
        exec:
          command:
            - "sh"
            - "-c"
            - "pg_isready"
            - "-U"
            - "$POSTGRES_USER"
        failureThreshold: 5
        periodSeconds: 10
        timeoutSeconds: 5
      resources: {}
      volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-lib-postgresql
          mountPath: /var/lib/postgresql
        - name: var-run-postgresql
          mountPath: /var/run/postgresql
    - name: auditlogger
      image: "gcr.io/k8s-staging-apisnoop/auditlogger:v20210824-0.2.0-70-g0faa7b3"
      imagePullPolicy: IfNotPresent
      env:
        - name: APP_DB_CONNECTION_STRING
          value: postgres://apisnoop:apisnoop@localhost/apisnoop?sslmode=disable
        - name: APP_DB_AUDIT_EVENT_TABLE
          value: testing.audit_event
        - name: APP_PORT
          value: "9900"
        - name: APP_DISABLE_LOGS
          value: "false"
      ports:
        - name: http
          containerPort: 9900
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: http
      readinessProbe:
        httpGet:
          path: /
          port: http
      resources: {}
